language: php
sudo: false
dist: trusty
php:
  - "5.5"
  - "5.6"
  - "7"
install:
  - composer update
  - composer dump-autoload -o
script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
after_script:
  - php vendor/bin/coveralls -v
